language: julia
os:
  - linux
  - osx
env:
    - ARCH="i686"
    - ARCH="x86_64"
julia:
  - 0.5
  - 0.6
  - nightly
matrix:
  exclude:
    - os: osx
      env: ARCH="i686"
    - julia: release
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("LMDB"); Pkg.test("LMDB"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("LMDB")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
